# Don't ask for confirmations
assume_yes = true
# Run specific steps - same options as the command line flag
only = ["containers", "firmware", "node", "shell", "system", "vim"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Display the time in step titles
display_time = true

# Cleanup temporary or old files
cleanup = true

[linux]
# Arch Package Manager to use. Allowed values: autodetect, trizen, paru, yay, pikaur, pacman.
arch_package_manager = "paru"
# Arguments to pass yay (or paru) when updating packages
#yay_arguments = "--nodevel"
show_arch_news = true
#trizen_arguments = "--devel"
#pikaur_arguments = ""
#enable_tlmgr = true
#emerge_sync_flags = "-q"
#emerge_update_flags = "-uDNa --with-bdeps=y world"
#redhat_distro_sync = false
#rpm_ostree = false

[npm]
# Use sudo if the NPM directory isn't owned by the current user
#use_sudo = true

[firmware]
# Offer to update firmware; if false just check for and display available updates
upgrade = true
